import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'SWE',
    company: 'Aprio Inc. dba Alex',
    logo: '/images/careers/alex.png',
    location: 'San Francisco, CA 🇺🇸',
    location_type: 'In-Person',
    type: 'Fulltime',
    start_date: '2025-11',
    end_date: null,
    industry: 'ai-hiring',
    link: 'https://alex.com/',
    responsibilities: [
      'Built Zoom + Recall.ai interview automation pipelines (OAuth, webhooks, transcript ingestion, media processing, cheating detection, fraud detection, etc) enabling real-time meeting capture and post-interview analytics.',
      'Remediated security vulnerabilities (IDOR, unauthenticated data exposure, NoSQL injection, path disclosure, etc) while implementing observability with Datadog (RUM, APM tracing, Logging, Monitors & Alerts).',
    ],
  },
  {
    position: 'SWE Intern',
    company: 'Abby Intelligence Inc.',
    logo: '/images/careers/abby.png',
    location: 'Hollywood, CA 🇺🇸',
    location_type: 'In-Person',
    type: 'Internship',
    start_date: '2025-07',
    end_date: '2025-11',
    industry: 'psychology-ai',
    link: 'https://abby.gg/',
    responsibilities: [
      'Built a crisis-agent with agents/sdk to assess crisis severity and trigger actions (e.g., emergency contact, account block, refunds, therapist alerts).',
      'Designed a multi-agent orchestration system for collaborative mental-health support across specialized agents.',
      'Implemented streaming with socket.io and mem0 for memory management for context-aware responses.',
    ],
  },
  {
    position: 'SWE Intern',
    company: 'Spatium Lab LLC',
    logo: '/images/careers/spatium_lab.png',
    location: 'Bellevue, WA 🇺🇸',
    location_type: 'In-Person',
    type: 'Contract',
    start_date: '2025-04',
    end_date: '2025-06',
    industry: 'space-tech',
    link: 'https://www.spatiumlab.com/',
    responsibilities: [
      'Used FastAPI & Next.js to implement different joint/flange type of calculators used by Space companies',
      'Created a scalable, multi-tenant architecture to support an end-to-end SaaS platform',
    ],
  },
  {
    position: 'SWE Intern',
    company: 'SPASHTA Inc.',
    logo: '/images/careers/spashta.png',
    location: 'Seattle, WA 🇺🇸',
    location_type: 'Remote',
    type: 'Internship',
    start_date: '2024-06',
    end_date: '2024-07',
    industry: 'machine-learning',
    link: 'https://spashta.ai/',
    responsibilities: [
      'Established virtual microphone and speaker systems using WDK, and SysVAD to simulate physical hardware.',
      'Used C++ rtAudio library for realtime audio streaming & portAudio to capture audio-buffers from virtual microphone/speaker to pass onto ML pipeline.',
      'Implemented WebRTC Noise Suppression, VAD to filter out silence and accent conversion through the ML pipeline.',
    ],
  },
  {
    position: 'SWE Intern',
    company: '(INTL FCStone) StoneX Inc.',
    logo: '/images/careers/stonex.webp',
    location: 'Pune, India 🇮🇳',
    location_type: 'Hybrid',
    type: 'Internship',
    start_date: '2023-01',
    end_date: '2023-07',
    industry: 'payments',
    link: 'https://www.stonex.com/',
    responsibilities: [
      'Designed and implemented the Single-Spa Micro-frontend architecture to seamlessly merge existing systems for a cross-border-payment web app, saving 30% development time and a 25% increase in overall project efficiency',
      'Established CICD pipelines for Azure-deployed micro-frontends reducing deployment time by 30% and improved overall code quality, maintaining a structured mono-repo for streamlined code management',
      'Deployed Okta & Casbin technology for robust SSO Authentication and precise user access controls',
      'Utilized React with TypeScript for different payment services like Rule-Engine, resulting in a 20% reduction in bug count and a 15% increase in overall application performance',
    ],
  },
  {
    position: 'SWE Intern',
    company: 'FairShare IT Services',
    logo: '/images/careers/fairshare.png',
    location: 'Pune, India 🇮🇳',
    location_type: 'Remote',
    type: 'Internship',
    start_date: '2021-08',
    end_date: '2021-11',
    industry: 'software',
    link: 'https://fairshare.tech/',
    responsibilities: [
      'Created an eCommerce platform for street grocery vendors using React.js and Firebase',
      'Engineered essential features including cart management, secure payment gateway, menus, and user profiles',
      'Utilized Firebase FireStore for database management and hosted the app on AWS',
    ],
  },
  {
    position: 'Co-Founder & CTO',
    company: 'SayItSocial PVT. LTD.',
    logo: '/images/careers/sayitsocial.svg',
    location: 'Pune, India 🇮🇳',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2019-06',
    end_date: '2021-09',
    industry: 'philo-tech',
    link: '#',
    responsibilities: [
      'Programmed an event-management web app to increase NGO-citizen interaction using React.js, Node.js, and MongoDB while leading a 6-person frontend team & 4-person backend team',
      'Designed pitch decks for investors and wrote detailed business plans to identify and onboard 8 key NGO clients',
    ],
  },
];
