import { ProjectsProps, ProjectItemProps } from '../types/projects';

export const PROJECTSLIST: ProjectsProps = {
  projects: [
    {
      title: 'Socraitive - Smart AI Teacher',
      slug: 'socraitive',
      description:
        'AI-powered knowledge testing platform with interactive dialogue, personalized testing, and deep learning experiences for students.',
      image: '/images/projects/socraitive.jpg',
      link_demo: 'https://devpost.com/software/socriative',
      link_github: '#',
      stacks: [
        'React.js',
        'Vite',
        'JavaScript',
        'Java',
        'Spring',
        'Azure',
        'OpenAI',
      ],
      content: '',
      is_show: true,
      is_featured: true,
      updated_at: new Date(),
    },
    {
      title: 'Greenie - BGV Startup',
      slug: 'greenie',
      description:
        'Background Verification System for Aadhar Card, Permanent Address, PAN, Driving Licence, Work Experience, etc.',
      image: '/images/projects/greenie.jpg',
      link_demo: 'https://greenie.one/',
      link_github: '#',
      stacks: [
        'Next.js',
        'Node.js',
        'TypeScript',
        'MongoDB',
        'Mantine',
        'SCSS',
        'Azure',
        'Docker',
        'Kubernetes',
      ],
      content: '',
      is_show: true,
      is_featured: true,
      updated_at: new Date(),
    },
    {
      title: '3D Tower Builder',
      slug: '3d-tower-builder',
      description:
        'The game typically involves stacking blocks over each other, aiming to create the tallest tower possible without it collapsing.',
      image: '/images/projects/towerbuilder.jpg',
      link_demo: 'https://swanand-wagh.github.io/3D-Tower-Builder/',
      link_github: 'https://github.com/Swanand-Wagh/3D-Tower-Builder',
      stacks: ['Unity3D', 'C#'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
    {
      title: 'Shot Boundary Detection System',
      slug: 'shot-boundary-detection-system',
      description:
        'Shot Boundary Detection System using Twin-comparison based approach, detecting cuts and gradual transitions in a video.',
      image: '/images/projects/shotboundarysystem.jpg',
      link_demo: 'https://shot-boundary-system.vercel.app/',
      link_github: 'https://github.com/Swanand-Wagh/Shot-Boundary-System',
      stacks: ['React.js', 'JavaScript', 'Python', 'CSS', 'HTML5'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
    {
      title: 'Image Retrieval System',
      slug: 'cbirs',
      description:
        'The system retrieves images using the Relevance Feedback, Color Code, and Intensity algorithms.',
      image: '/images/projects/cbir.jpg',
      link_demo: 'https://alias-image-retrieval.vercel.app/',
      link_github: 'https://github.com/Swanand-Wagh/Image-Retrieval-System',
      stacks: ['React.js', 'JavaScript', 'CSS', 'HTML5'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
    {
      title: 'Charity DAO',
      slug: 'project-2',
      description:
        'Blockchain based Fundraising System to enhance security & transparency for NGOs and volunteers.',
      image: '/images/projects/charitydao.jpg',
      link_demo: 'https://alias-charity-dao.vercel.app/',
      link_github: 'https://github.com/Swanand-Wagh/Alias-Charity-DAO',
      stacks: ['React.js', 'JavaScript', 'Solidity', 'IPFS', 'CSS', 'HTML5'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
    {
      title: 'Covid Tracker',
      slug: 'covid-tracker',
      description:
        'A covid19 cases tracking web-app built using ReactJs. Disease.sh api used to fetch real-time data',
      image: '/images/projects/covidtracker.jpg',
      link_demo: 'https://alias-covid-tracker.web.app/',
      link_github: 'https://github.com/Swanand-Wagh/Alias-Covid-Tracker',
      stacks: ['React.js', 'JavaScript', 'CSS', 'HTML5'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
  ],
};
